version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: psql
      POSTGRES_USER: psql
      POSTGRES_DB: dwh_db
    ports:
      - 5433:5432
    restart: always